apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-sample
  namespace: test-sample
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: docker-sample
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docker-sample
    spec:
      containers:
      - name: app
        image: docker-sample
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: Asia/Tehran
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 50
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5